-- Series
INSERT INTO catalog_series (id, name) VALUES
('1', 'The Empyrean'),
('2', 'ACOTAR'),
('3', 'Crescent City'),
('4', 'Blood and Ash'),
('5', 'The Powerless Trilogy'),
('6', 'The Folk of the Air'),
('7', 'Kingdom of the Wicked'),
('8', 'Throne of Glass'),
('9', 'The Bridge Kingdom'),
('10', 'These Hollow Vows'),
('11', 'Celestial Kingdom'),
('12', 'Cat and Mouse Duet'),
('13', 'Legacy of Gods'),
('14', 'The Ruinous Love Trilogy'),
('15', 'Devil''s Night'),
('16', 'Fall Away'),
('17', 'Twisted'),
('18', 'Kings of Sin'),
('19', 'Maple Hills'),
('20', 'Windy City'),
('21', 'Vancouver Storm'),
('22', 'Born in Blood Mafia Chronicles'),
('23', 'Made'),
('24', 'Knockemout'),
('25', 'Shatter Me'),
('26', 'Zodiac Academy'),
('27', 'Caraval'),
('28', 'Alex Stern'),
('29', 'Six of Crows'),
('30', 'Hades & Persephone'),
('31', 'The Atlas'),
('32', 'Dark Olympus'),
('33', 'Outlander'),
('34', 'The Burning Kingdoms'),
('35', 'Serpent & Dove'),
('36', 'Letters of Enchantment'),
('37', 'Once Upon a Broken Heart'),
('38', 'The Grisha'),
('39', 'The Mortal Instruments'),
('40', 'The Infernal Devices'),
('41', 'Bellinger Sisters'),
('42', 'A Vine Mess')
ON CONFLICT DO NOTHING;