-- Book vibes
INSERT INTO catalog_book_vibes (id, book_id, vibe_text, sort_order) VALUES
(1, '1', 'He''s her enemy. He''s also the only one who''d burn the world for her. 🔥', 0),
(2, '1', 'Dragons choose you or you die. No retakes, no second chances.', 1),
(3, '1', 'The slow burn will have you screaming at 2am. Worth it.', 2),
(4, '1', '"Touch her and find out" energy — but with actual dragons. 🐉', 3),
(5, '2', 'Everything you thought you knew? Lies. ALL of it. 💀', 0),
(6, '2', 'He''ll betray everyone to keep her safe. Even her.', 1),
(7, '2', 'The angst is so thick you could cut it with a sword.', 2),
(8, '2', 'Trust no one. Especially not the ones you love.', 3),
(9, '3', 'She thinks she''s saving him. She has no idea what''s coming. 🌹', 0),
(10, '3', 'Book 1 is the appetizer. Book 2 will WRECK you.', 1),
(11, '3', 'Beauty and the Beast but make it fae and unhinged.', 2),
(12, '3', 'You''ll hate who you love and love who you hate.', 3),
(13, '4', 'The greatest book boyfriend redemption arc in history. Period. 👑', 0),
(14, '4', 'She was broken. He waited. That''s it. That''s the book. 😭', 1),
(15, '4', 'You will literally throw ACOTAR across the room and pick THIS up.', 2),
(16, '4', '"I would have been gentle with you, too." — if you know, you know.', 3),
(17, '5', 'She went from prey to the most powerful thing in the room. 🔥', 0),
(18, '5', 'The found family content will heal your soul.', 1),
(19, '5', 'War is coming and you will feel EVERYTHING.', 2),
(20, '5', 'The bat boys. That''s it. That''s the vibe.', 3),
(21, '6', 'She''s a mess. He''s patient. The tension is UNREAL. 🔥', 0),
(22, '6', 'The spiciest ACOTAR book and it''s not even close.', 1),
(23, '6', 'Her healing arc will make you sob on the treadmill.', 2),
(24, '6', 'Nesta Archeron supremacy. That''s all. 👑', 3),
(25, '7', '800 pages and you won''t want it to end. 📖', 0),
(26, '7', 'The last 100 pages will ruin you for a week.', 1),
(27, '7', 'Fantasy meets modern city vibes — clubs, phones, AND magic.', 2),
(28, '7', 'Push through the first 200 pages. Trust. Me.', 3),
(29, '8', 'He''s not allowed to touch her. He can''t stop. 🫣', 0),
(30, '8', 'The plot twist will make you restart the book immediately.', 1),
(31, '8', 'Possessive hero energy at level 1000.', 2),
(32, '8', '"What if he''s not who you think he is?" — CORRECT.', 3),
(33, '9', 'She''s the only one without powers. She''s also the most dangerous. 💪', 0),
(34, '9', 'He falls first AND he falls HARD.', 1),
(35, '9', 'Hunger Games meets enemies-to-lovers and it works perfectly.', 2),
(36, '9', 'The secret identity reveal will END you.', 3),
(37, '10', 'The pining in this book is AGGRESSIVE. 😩', 0),
(38, '10', 'He can''t stay away. She won''t let him close.', 1),
(39, '10', 'More betrayal, more angst, more "WHY."', 2),
(40, '10', 'Second book syndrome? She doesn''t know her.', 3),
(41, '11', 'He torments her. She outplays him. The tension is ELECTRIC. ⚡', 0),
(42, '11', 'She''s human in a world of faeries. She''s also the scariest one there.', 1),
(43, '11', 'The enemies part is REAL. Like actually hate each other.', 2),
(44, '11', 'Jude Duarte doesn''t need saving. She needs a crown. 👑', 3),
(45, '12', 'A witch and the devil walk into a murder mystery... 🔮', 0),
(46, '12', 'He''s literally the Prince of Hell. You''ll still simp.', 1),
(47, '12', 'Italian setting, dark magic, and tension you can TASTE.', 2),
(48, '12', 'The slow burn across 3 books is *chef''s kiss*.', 3),
(49, '13', 'She''s an assassin. In a competition. With boys who underestimate her. 🗡️', 0),
(50, '13', 'Book 1 is YA. By book 3 you''ll need therapy.', 1),
(51, '13', 'The series glow-up is the greatest in fantasy history.', 2),
(52, '13', 'Start here if you want to fall in love with SJM forever.', 3),
(53, '14', 'She was sent to destroy him. She fell in love instead. 💔', 0),
(54, '14', 'The betrayal reveal will PHYSICALLY hurt you.', 1),
(55, '14', 'Underrated enemies-to-lovers that deserves more hype.', 2),
(56, '14', 'Arranged marriage where both are playing each other. Chef''s kiss.', 3),
(57, '15', 'Two fae princes. Both want her. Neither is telling the truth. 👀', 0),
(58, '15', 'The love triangle where you genuinely can''t choose.', 1),
(59, '15', 'Faerie deals, stolen thrones, and trust issues.', 2),
(60, '15', 'ACOTAR vibes but with more deception.', 3),
(61, '16', 'Chinese mythology retold with the most beautiful prose. ✨', 0),
(62, '16', 'Slow burn so slow you''ll beg for a crumb of romance.', 1),
(63, '16', 'She hides who she is to save her mother. The loyalty is real.', 2),
(64, '16', 'If you love lush worldbuilding and gentle romance — this is it.', 3),
(65, '17', '12 Dancing Princesses retelling but make it HORROR. 💀', 0),
(66, '17', 'Sisters keep dying and no one will say why.', 1),
(67, '17', 'Gothic manor, creepy sea, trust nobody.', 2),
(68, '17', 'The atmosphere alone will give you chills.', 3),
(69, '18', '827 pages of dragon queens, women warriors, and sapphic love. 🐉', 0),
(70, '18', 'Epic fantasy that doesn''t need a man to save the world.', 1),
(71, '18', 'If you want Game of Thrones but feminist — here.', 2),
(72, '18', 'The world-building is so rich you''ll need a map (there is one).', 3),
(73, '19', 'He watches her. She knows. She shouldn''t like it. She does. 👁️', 0),
(74, '19', 'This is NOT a safe book. You''ve been warned. You''ll read it anyway.', 1),
(75, '19', 'Morally grey? No. Morally VOID. And you''ll be obsessed.', 2),
(76, '19', 'The definition of "I can fix him" — except you can''t. And you won''t want to. 💀', 3),
(77, '20', 'Book 1 was dark. Book 2 is DEVASTATING. 💔', 0),
(78, '20', 'He will burn the world to find her. And he does.', 1),
(79, '20', 'Content warnings exist for a reason. Read them.', 2),
(80, '20', 'The most intense rescue arc in dark romance. Period.', 3),
(81, '21', 'He wears a mask. She shouldn''t want to know what''s underneath. 🎭', 0),
(82, '21', 'Bully romance but make it elite, dark, and completely unhinged.', 1),
(83, '21', 'He doesn''t do feelings. Until her. Then he does them violently.', 2),
(84, '21', 'If "possessive" and "obsessed" are your love languages — welcome home.', 3),
(85, '22', 'Four men. All dangerous. All hers. ALL obsessed. 🐍', 0),
(86, '22', 'Reverse harem where every guy is worse than the last (compliment).', 1),
(87, '22', 'She was supposed to be a debt. She became their queen.', 2),
(88, '22', 'If you want one possessive hero — here''s FOUR.', 3),
(89, '23', 'Two serial killers who only kill bad people fall in love. Yes, really. 🔪❤️', 0),
(90, '23', 'The most unhinged rom-com you''ll ever read.', 1),
(91, '23', 'Dark romance but make it FUNNY and wholesome??', 2),
(92, '23', 'You''ll laugh, you''ll swoon, you''ll question your morals.', 3),
(93, '24', 'Three years ago they destroyed her. Now they''re back. 🎃', 0),
(94, '24', 'Masks, revenge, and a night where anything goes.', 1),
(95, '24', 'The OG bully romance that started it all.', 2),
(96, '24', 'Devil''s Night is not Halloween. It''s worse.', 3),
(97, '25', 'He was her best friend. Then he made her life hell. WHY. 😭', 0),
(98, '25', 'The angst of not knowing why he turned on her will CONSUME you.', 1),
(99, '25', 'Childhood friends to enemies to "oh no" to lovers.', 2),
(100, '25', 'She doesn''t break. That''s what makes it so good.', 3),
(101, '26', 'Snowed in. Middle of nowhere. Three men. Zero rules. ❄️', 0),
(102, '26', 'The most taboo PenDog book and that''s saying something.', 1),
(103, '26', 'If you need content warnings — YES. All of them.', 2),
(104, '26', 'You''ll either DNF in chapter 2 or devour it in one sitting.', 3),
(105, '27', 'She''s dating his son. She lives in his house. The tension is ILLEGAL. 🎂', 0),
(106, '27', 'Age gap done RIGHT — respectful but still scorching.', 1),
(107, '27', 'The pining is so quiet and painful you''ll combust.', 2),
(108, '27', 'PenDog''s best standalone. Fight me.', 3),
(109, '28', 'Pen pals for years. He shows up at her school. She doesn''t recognize him. 📝', 0),
(110, '28', 'He knows exactly who she is. She has no idea.', 1),
(111, '28', 'The identity reveal is *everything*.', 2),
(112, '28', 'Angsty, messy, unhinged teenagers. Peak PenDog.', 3),
(113, '29', 'He doesn''t feel emotions. Until her. Then he feels ALL of them. 🖤', 0),
(114, '29', 'Brother''s best friend who would literally commit crimes for her.', 1),
(115, '29', 'Cold, calculating, billionaire genius — melted by sunshine girl.', 2),
(116, '29', 'The Ana Huang gateway drug. You''ll read all four.', 3),
(117, '30', 'He''s her bodyguard. He''s NOT supposed to want her. He does. Badly. 🛡️', 0),
(118, '30', 'Princess + protector who''d start wars for her.', 1),
(119, '30', 'The forbidden aspect makes every touch feel electric.', 2),
(120, '30', 'Rhys but make him modern, military, and UNHINGED.', 3),
(121, '31', 'They HATE each other. The chemistry says otherwise. 🔥', 0),
(122, '31', 'The spiciest Twisted book. By far.', 1),
(123, '31', 'She''s a brat. He can''t stand her. They can''t stop. 😏', 2),
(124, '31', 'Enemies with benefits has never been this chaotic.', 3),
(125, '32', 'He controls everything. Except how he feels about her. 🕸️', 0),
(126, '32', 'Fake dating a man who''s secretly been obsessed with you for years.', 1),
(127, '32', 'Christian Harper is the blueprint for morally grey billionaires.', 2),
(128, '32', 'The best Twisted book. Yes, I''m picking sides.', 3),
(129, '33', 'You''ll think you know who the villain is. You don''t. 💔', 0),
(130, '33', 'This will make you ugly cry on public transport. Bring tissues.', 1),
(131, '33', 'It''s not about romance. It''s about the hardest choice you''ll ever understand.', 2),
(132, '33', '"Just keep swimming" but make it heartbreaking and real.', 3),
(133, '34', 'The healing sequel you needed after IEWU. 🩹', 0),
(134, '34', 'Atlas finally gets his story and you WILL cry.', 1),
(135, '34', 'Less pain, more hope — but still emotional.', 2),
(136, '34', 'Second chances done right.', 3),
(137, '35', '"Don''t ask me about my past. Don''t expect a future." 💔', 0),
(138, '35', 'The dual timeline will slowly destroy you.', 1),
(139, '35', 'He has one rule: no feelings. Guess how that goes.', 2),
(140, '35', 'You''ll understand the title at the end and SOB.', 3),
(141, '36', 'You''ll finish this book and stare at the wall for 30 minutes. 🧱', 0),
(142, '36', 'Is she lying? Is SHE lying? Is everyone lying? YES.', 1),
(143, '36', 'The last page will make you restart the book immediately.', 2),
(144, '36', 'Do NOT read the reviews. Do NOT let anyone spoil this. Just read it. 💀', 3),
(145, '37', 'They meet once a year. Same day. Every year. For five years. 📅', 0),
(146, '37', 'You''ll think it''s cute. Then the twist hits. HARD.', 1),
(147, '37', 'CoHo''s most underrated book and I will die on this hill.', 2),
(148, '37', 'The ending will make you rethink EVERYTHING.', 3),
(149, '38', 'People anonymously confess secrets. He paints them. She IS one. 🎨', 0),
(150, '38', 'Art, secrets, and a love built on lies.', 1),
(151, '38', 'Quiet CoHo but the emotional punch is still there.', 2),
(152, '38', 'The confessions are real and they''ll haunt you.', 3),
(153, '39', 'Fake dating your hot professor. What could go wrong? Everything. 🧪', 0),
(154, '39', 'He''s 6''4", grumpy, and looks at her like she hung the stars.', 1),
(155, '39', 'She''s a STEM queen who can''t figure out her own love life. Mood.', 2),
(156, '39', 'The hand on the thigh scene. You''ll know it when you get there. 🔥', 3),
(157, '40', 'He''s been in love with her for YEARS. She thinks he hates her. 🧠', 0),
(158, '40', 'NASA setting + rivals + secret pining = perfection.', 1),
(159, '40', 'If you loved TLH, this is the same energy but rivals.', 2),
(160, '40', 'The miscommunication is frustrating in the BEST way.', 3),
(161, '41', 'Two writers swap genres for the summer. Chaos ensues. ✍️', 0),
(162, '41', 'She writes rom-coms. He writes literary fiction. The TENSION.', 1),
(163, '41', 'Emily Henry invented the modern rom-com. This is proof.', 2),
(164, '41', 'Funny until it''s not — then it hits you right in the chest.', 3),
(165, '42', 'Best friends. One trip ruined everything. Now she wants him back. ✈️', 0),
(166, '42', 'The dual timeline will make you laugh AND cry.', 1),
(167, '42', 'He''s quiet. She''s chaos. They''re soulmates. Obviously.', 2),
(168, '42', 'The hotel room scene. You''ll know. 🫠', 3),
(169, '43', 'A book about a book editor who IS the love interest, not the small-town girl. 📚', 0),
(170, '43', 'Finally — a heroine who''s ambitious and doesn''t apologize.', 1),
(171, '43', 'Hallmark movie setup but make it self-aware and smart.', 2),
(172, '43', 'Charlie Lastra is the book boyfriend you didn''t know you needed.', 3),
(173, '44', 'They broke up. Their friends don''t know. One week. One bed. 🏠', 0),
(174, '44', 'Pretending to still be together while DYING inside.', 1),
(175, '44', 'Emily Henry''s most emotional book — bring tissues.', 2),
(176, '44', 'The flashbacks will slowly break your heart and rebuild it.', 3),
(177, '45', 'Their exes left them for each other. So they team up. Obviously. 😏', 0),
(178, '45', 'Revenge plot turned real feelings — classic.', 1),
(179, '45', 'Miles is soft boy energy with an edge.', 2),
(180, '45', 'Emily Henry keeps delivering and we keep reading.', 3),
(181, '46', 'Arranged marriage to a billionaire who despises her. Until he doesn''t. 💍', 0),
(182, '46', 'He''s cold. She''s sunshine. The meltdown is GLORIOUS.', 1),
(183, '46', 'Ana Huang said "let me create the perfect book boyfriend" and DID.', 2),
(184, '46', 'The groveling. THE GROVELING. 🧎‍♂️', 3),
(185, '47', 'He''s perfect. Controlled. Composed. She ruins all of that. 🫠', 0),
(186, '47', 'Forbidden because of his family''s reputation — makes it hotter.', 1),
(187, '47', 'The British hero content we deserve.', 2),
(188, '47', 'Slow burn that actually BUILDS and pays off.', 3),
(189, '48', 'He lost her. Now he''ll do ANYTHING to get her back. 💔', 0),
(190, '48', 'The grovel is ELITE. Like, top-tier, chef''s kiss grovel.', 1),
(191, '48', 'He chose work over her. Biggest mistake of his life.', 2),
(192, '48', 'If you love watching a man BEG — this is your book.', 3),
(193, '49', 'He''s a hockey captain. She''s a figure skater. He''s SO gone for her. 🏒', 0),
(194, '49', 'Grumpy sunshine but he''s a giant golden retriever in disguise.', 1),
(195, '49', 'The size difference content you didn''t know you needed.', 2),
(196, '49', 'Comfort read energy with spice that sneaks up on you. 🌶️', 3),
(197, '50', 'She''s a camp counselor. He''s... also there. Against his will. 🏕️', 0),
(198, '50', 'Enemies to lovers but they''re both STUBBORN.', 1),
(199, '50', 'Summer camp vibes but make it adult and spicy.', 2),
(200, '50', 'Russ is the golden retriever boyfriend of your dreams.', 3),
(201, '51', 'He''s her brother''s best friend. He''s been waiting for YEARS. 😩', 0),
(202, '51', 'The pining is so painful it should be illegal.', 1),
(203, '51', 'Bookish heroine + hockey player = the content we deserve.', 2),
(204, '51', 'Friends to lovers where he was NEVER just a friend.', 3),
(205, '52', 'He''s the grumpiest NBA player alive. She''s a flight attendant made of sunshine. ✈️', 0),
(206, '52', 'Fake dating on the team plane. In first class. With FEELINGS.', 1),
(207, '52', 'He''s terrifying to everyone except her.', 2),
(208, '52', 'Zanders is the possessive hero blueprint. Period. 🏀', 3),
(209, '53', 'She needs a roommate. He needs to not fall in love. Oops. 🏠', 0),
(210, '53', 'Single mom + baseball player who''s soft for her kid.', 1),
(211, '53', 'The slow burn is TORTURE but so worth it.', 2),
(212, '53', 'He moves her stuff in without asking. Possessive but make it wholesome.', 3),
(213, '54', 'He''s a grumpy hockey goalie. She moves into his house. He''s doomed. 🥅', 0),
(214, '54', 'Broken hero who heals through loving her — my Roman Empire.', 1),
(215, '54', 'The size difference moments will make you feral.', 2),
(216, '54', 'Comfort sports romance with actual emotional depth.', 3),
(217, '55', 'She''s married off to a mafia boss she''s never met. Wedding night and all. 💀', 0),
(218, '55', 'The OG mafia romance that started a whole subgenre.', 1),
(219, '55', 'He''s terrifying to everyone. Gentle with her. Eventually.', 2),
(220, '55', 'If you want mafia romance — start here.', 3),
(221, '56', 'She''s engaged to one brother. She wants the other. The WRONG one. 👀', 0),
(222, '56', 'Italian mafia + forbidden attraction = chef''s kiss.', 1),
(223, '56', 'He''s silent, deadly, and looks at her like she''s his religion.', 2),
(224, '56', 'Danielle Lori writes tension like no one else.', 3),
(225, '57', 'He''s a fed. She''s a mafia wife. They should NOT want each other. 🔥', 0),
(226, '57', 'The best Made book — fight me on this.', 1),
(227, '57', 'Cat and mouse where both are predators.', 2),
(228, '57', 'Christian Allister lives in my head rent-free. Forever.', 3),
(229, '58', 'You know how it ends. You read it anyway. You cry anyway. 😭', 0),
(230, '58', 'The most beautiful love story ever written. I said what I said.', 1),
(231, '58', '"I could recognize him by touch alone." — PAIN.', 2),
(232, '58', 'Greek mythology but it''s about love, not war.', 3),
(233, '59', 'She was an outcast goddess. She became the most powerful witch alive. 🌿', 0),
(234, '59', 'Feminist retelling of Greek mythology done RIGHT.', 1),
(235, '59', 'The prose is so gorgeous you''ll want to highlight every page.', 2),
(236, '59', 'Slow, quiet power. The best kind.', 3),
(237, '60', 'Seven husbands. One true love. And she''s not who you think. 💋', 0),
(238, '60', 'Old Hollywood glamour hiding the most devastating love story.', 1),
(239, '60', 'You''ll think about Evelyn Hugo for MONTHS after finishing.', 2),
(240, '60', 'The twist at the end connects everything. Perfectly. 🌟', 3),
(241, '61', 'She needs a fake date to a wedding in Spain. He volunteers. WHY. 🇪🇸', 0),
(242, '61', 'Coworkers who "hate" each other. Sure, Jan.', 1),
(243, '61', 'He''s been in love with her the WHOLE TIME.', 2),
(244, '61', 'The wedding scenes will give you actual butterflies.', 3),
(245, '62', 'Her apartment floods. His couch is available. One problem: he''s gorgeous. 🛋️', 0),
(246, '62', 'He cooks for her. Carries her. Calls her beautiful in Spanish.', 1),
(247, '62', 'The adventure dates are the most romantic thing ever written.', 2),
(248, '62', 'Lucas Martín is BookTok''s boyfriend and I understand why.', 3),
(249, '63', 'He''s the town grump. She shows up with a stolen car and a baby. 👶', 0),
(250, '63', 'Knox Morgan will ruin all other book boyfriends for you.', 1),
(251, '63', 'Small town romance but make it 573 pages and worth every one.', 2),
(252, '63', 'He says he doesn''t care. He literally fights people for her.', 3),
(253, '64', 'He''s a chief of police recovering from being shot. She won''t leave him alone. 👮', 0),
(254, '64', 'Hurt/comfort done SO well — she heals him by being annoying.', 1),
(255, '64', 'Nash Morgan is soft grumpy king.', 2),
(256, '64', 'The Knockemout boys are a package deal and we love them all.', 3),
(257, '65', 'He collects her kisses in a jar. Every single one. 💔', 0),
(258, '65', 'You WILL cry. Not might. WILL.', 1),
(259, '65', 'Childhood sweethearts and a love that''s bigger than everything.', 2),
(260, '65', 'Read this when you want to feel everything at once.', 3),
(261, '66', 'She made a deal to live forever. The price: no one remembers her. Ever. 🖤', 0),
(262, '66', '300 years of being forgotten. Then one person remembers.', 1),
(263, '66', 'The most beautiful premise in fantasy. Period.', 2),
(264, '66', 'You''ll think about this book at random moments for years.', 3),
(265, '67', 'Her touch is lethal. He wants her to be a weapon. She wants to be free. ✋', 0),
(266, '67', 'The strikethrough text style is genius and heartbreaking.', 1),
(267, '67', 'Team Warner vs Team Adam — choose wisely.', 2),
(268, '67', 'Dystopia meets romance in the most poetic way possible.', 3),
(269, '68', 'They share an office. They play games. One of them is losing on purpose. 🎯', 0),
(270, '68', 'The elevator scene is ICONIC.', 1),
(271, '68', 'OG enemies-to-lovers office romance. The blueprint.', 2),
(272, '68', 'He memorized the exact shade of her eyes. He''s GONE.', 3),
(273, '69', 'She hires an escort to teach her about intimacy. He catches feelings. 💕', 0),
(274, '69', 'Autistic heroine written with such care and authenticity.', 1),
(275, '69', 'He''s supposed to be the teacher. He becomes the student.', 2),
(276, '69', 'Spicy, sweet, and SO well-written.', 3),
(277, '70', 'She quits. He shows up at her door. "Marry me." EXCUSE ME?! 💍', 0),
(278, '70', 'The SLOWEST burn ever. 598 pages. Worth every single one.', 1),
(279, '70', 'He''s a 6''4" NFL player who can''t function without her.', 2),
(280, '70', 'Mariana Zapata invented slow burn. This is her masterpiece.', 3),
(281, '71', 'Figure skating partners who can''t stand each other. The BANTER. ⛸️', 0),
(282, '71', '531 pages of slow burn figure skating enemies to lovers.', 1),
(283, '71', 'She''s stubborn. He''s patient. It takes FOREVER. Worth it.', 2),
(284, '71', 'The moment he finally snaps? *chef''s kiss* 🤌', 3),
(285, '72', 'Her childhood hero is now her coach. He''s rude. She''s unimpressed. ⚽', 0),
(286, '72', 'Another MZ slow burn that takes 500+ pages. No complaints.', 1),
(287, '72', 'She doesn''t fangirl. That''s what gets him.', 2),
(288, '72', 'The respect she earns from him is better than any kiss.', 3),
(289, '73', 'Twin sisters discover they''re fae royalty. The heirs want them GONE. 👑', 0),
(290, '73', '8 books of slow burn enemies to lovers. EIGHT. Buckle up.', 1),
(291, '73', 'The bullying is BRUTAL. The payoff is worth it.', 2),
(292, '73', 'BookTok''s most divisive series — you''ll love it or rage-read it.', 3),
(293, '74', 'A magical game where nothing is real. Except the danger. 🎪', 0),
(294, '74', 'The Night Circus vibes but YA and more romantic.', 1),
(295, '74', 'Trust nothing. Question everything. Enjoy the ride.', 2),
(296, '74', 'The aesthetic alone will pull you in — dark carnival magic. ✨', 3),
(297, '75', 'A black and white circus that appears without warning. Two magicians. One competition. 🎩', 0),
(298, '75', 'The most atmospheric book you''ll ever read.', 1),
(299, '75', 'Love told through magic and creation, not words.', 2),
(300, '75', 'Read this in autumn with candles. Trust me. 🕯️', 3),
(301, '76', 'Yale''s secret societies practice real magic. She''s sent to police them. 🏛️', 0),
(302, '76', 'Dark academia but make it actually dark. Like, murder dark.', 1),
(303, '76', 'Alex Stern is the most badass heroine Bardugo''s written.', 2),
(304, '76', 'If you want Six of Crows energy but adult — HERE.', 3),
(305, '77', 'Six outcasts. One impossible heist. Zero spice but ALL the tension. 🃏', 0),
(306, '77', 'Kaz Brekker is the morally grey king. No competition.', 1),
(307, '77', 'The found family content will HEAL you.', 2),
(308, '77', '"No mourners, no funerals." — and now you''re emotionally invested.', 3),
(309, '78', 'The sequel that''s somehow BETTER than the first. 👑', 0),
(310, '78', 'Every couple gets their moment and it''s PERFECT.', 1),
(311, '78', 'The schemes are wilder. The stakes are higher. The feels are REAL.', 2),
(312, '78', '"I would come for you." — I''m not crying, you''re crying. 😭', 3),
(313, '79', '838 pages. The crossover event of the SJM universe. 🌌', 0),
(314, '79', 'If you''ve read ACOTAR and CC — the payoff is INSANE.', 1),
(315, '79', 'Bryce Quinlan doesn''t play. She DELIVERS.', 2),
(316, '79', 'The ending sets up something massive. We''re not ready.', 3),
(317, '80', 'She''s his assistant. He''s the villain. She brings him coffee and chaos. ☕', 0),
(318, '80', 'Cozy fantasy where the villain is soft for ONE person.', 1),
(319, '80', 'If you want light, funny fantasy with zero stress — this is it.', 2),
(320, '80', 'He''s evil to everyone except her and it''s ADORABLE.', 3),
(321, '81', 'Scarlett St. Clair said "let me make it darker" and DELIVERED. 🖤', 0),
(322, '81', 'Arranged marriage to a monster who worships her.', 1),
(323, '81', 'If you loved Hades & Persephone — this is the unhinged cousin.', 2),
(324, '81', 'Dark fantasy romance with zero apologies.', 3),
(325, '82', 'Persephone meets Hades at a club. He''s OBSESSED immediately. 🔥', 0),
(326, '82', 'Greek mythology retelling but make it modern and spicy.', 1),
(327, '82', 'He''s the God of the Dead. She makes him feel alive.', 2),
(328, '82', 'The Hades & Persephone retelling that started it all on BookTok.', 3),
(329, '83', 'He hasn''t spoken in years. She teaches him sign language. He falls. 🤟', 0),
(330, '83', 'The softest, most tender romance you''ll ever read.', 1),
(331, '83', 'Broken hero who heals through love — done PERFECTLY.', 2),
(332, '83', 'You will cry happy tears AND sad tears. Probably at the same time.', 3),
(333, '84', 'Six magicians. One spot. Someone won''t survive the selection. 💀', 0),
(334, '84', 'Dark academia meets fantasy with morally bankrupt geniuses.', 1),
(335, '84', 'Everyone is smart, everyone is hot, everyone is suspicious.', 2),
(336, '84', 'The Secret History but with actual magic.', 3),
(337, '85', 'Vampire girl married to a werewolf alpha. For politics. Feelings not included. 🐺', 0),
(338, '85', 'Ali Hazelwood said "let me try paranormal" and ATE.', 1),
(339, '85', 'He''s massive, grumpy, and so confused by his feelings for her.', 2),
(340, '85', 'Size difference content that will make you FERAL.', 3),
(341, '86', 'Chess prodigy vs world champion. She beats him. He''s in love. ♟️', 0),
(342, '86', 'YA Ali Hazelwood — all the banter, less spice, same heart.', 1),
(343, '86', 'Rivals who respect each other''s genius? YES.', 2),
(344, '86', 'The chess scenes are somehow more tense than any love scene.', 3),
(345, '87', 'Dark academia on a cliff. Mysterious professor. Gothic castle. YES. 🏰', 0),
(346, '87', 'The atmosphere is so thick you can TASTE it.', 1),
(347, '87', 'He''s her professor. He''s also something else entirely.', 2),
(348, '87', 'If dark academia is your aesthetic — this is your book.', 3),
(349, '88', 'He discovers his wife has been lying about EVERYTHING. 💔', 0),
(350, '88', 'Romance meets thriller in the most unsettling way.', 1),
(351, '88', 'You think you know her. You don''t. At all.', 2),
(352, '88', 'The twist reframes the entire book. Brilliant.', 3),
(353, '89', 'Persephone runs from an arranged marriage. Hades catches her. 🖤', 0),
(354, '89', 'Modern Olympus retelling that''s 90% spice and 100% addictive.', 1),
(355, '89', 'He''s the man everyone fears. She makes him kneel.', 2),
(356, '89', 'The praise kink content in this series is LEGENDARY. 🔥', 3),
(357, '90', 'He''s sent to kill her. He marries her instead. Classic. 💀💍', 0),
(358, '90', 'Eros retelling where the hit man catches feelings.', 1),
(359, '90', 'She''s soft. He''s lethal. Together they''re chaotic perfection.', 2),
(360, '90', 'Somehow the funniest AND spiciest Dark Olympus book.', 3),
(361, '91', 'Achilles, Patroclus, and Helen. Yes, all three. Together. ⚔️', 0),
(362, '91', 'The MMF content Dark Olympus fans were WAITING for.', 1),
(363, '91', 'She wants the throne. They want her. Everyone wins.', 2),
(364, '91', 'Katee Robert said "why choose?" and wrote this.', 3),
(365, '92', 'She touches a stone and wakes up in 1743 Scotland. With a hot Highlander. 🏴󠁧󠁢󠁳󠁣󠁴󠁿', 0),
(366, '92', '850 pages of historical romance perfection.', 1),
(367, '92', 'Jamie Fraser is the OG book boyfriend. Accept no substitutes.', 2),
(368, '92', 'Time travel romance before it was cool. Still unmatched.', 3),
(369, '93', 'A captive princess and a maidservant with a deadly secret. 🌺', 0),
(370, '93', 'Indian-inspired fantasy with sapphic slow burn.', 1),
(371, '93', 'The politics are as sharp as the romance.', 2),
(372, '93', 'Beautiful, brutal, and completely unforgettable.', 3),
(373, '94', 'She controls the king. He hates it. He also loves it. 👑', 0),
(374, '94', 'The power games between Jude and Cardan are ADDICTIVE.', 1),
(375, '94', 'That ending will make you throw the book. Then grab book 3.', 2),
(376, '94', 'Middle book syndrome? She doesn''t know her.', 3),
(377, '95', 'She went from mortal girl to High Queen. The glow-up is REAL. 👑', 0),
(378, '95', 'Cardan''s confession scene lives rent-free in everyone''s head.', 1),
(379, '95', 'The trilogy finale that actually DELIVERS.', 2),
(380, '95', '"You are the first and last thing on my mind" — CARDAN. 😭', 3),
(381, '96', 'A witch married to a witch hunter. What could go wrong? EVERYTHING. 🐍', 0),
(382, '96', 'He hunts her kind. She IS her kind. The irony is *chef''s kiss*.', 1),
(383, '96', 'Enemies to lovers where the stakes are literally life or death.', 2),
(384, '96', 'French-inspired fantasy with banter that SLAPS.', 3),
(385, '97', 'Libraries are alive. Books are dangerous. She protects them. 📚', 0),
(386, '97', 'Bookish heroine + mysterious sorcerer + sentient libraries.', 1),
(387, '97', 'Cozy fantasy with just enough danger to keep you hooked.', 2),
(388, '97', 'If you''re a book lover — this was written FOR you.', 3),
(389, '98', 'Rival journalists writing letters through a magical wardrobe. 💌', 0),
(390, '98', 'The love letters will DESTROY you in the best way.', 1),
(391, '98', 'War, words, and a love that transcends everything.', 2),
(392, '98', 'BookTok''s darling of 2023 for a REASON.', 3),
(393, '99', 'He doesn''t remember her. She remembers everything. 💔', 0),
(394, '99', 'The amnesia trope done so painfully RIGHT.', 1),
(395, '99', 'Reading their letters knowing he forgot — pure AGONY.', 2),
(396, '99', 'The sequel that broke every Divine Rivals fan. Worth the pain.', 3),
(397, '100', 'She''s a goddess now. The problems are BIGGER. 🔱', 0),
(398, '100', 'More angst, more miscommunication, more Hades being obsessed.', 1),
(399, '100', 'Their love is tested and it HURTS.', 2),
(400, '100', 'The spice level went UP and we''re not complaining.', 3),
(401, '101', 'The war is here. The secrets are worse. Nobody is safe. ⚔️', 0),
(402, '101', 'Violet Sorrengail in her most powerful era yet.', 1),
(403, '101', 'The cliffhanger will make you need book 4 IMMEDIATELY.', 2),
(404, '101', 'Everything you feared? It''s happening.', 3),
(405, '102', 'The cozy holiday novella between the chaos. ❄️', 0),
(406, '102', 'Feyre and Rhys being domestic is everything you need.', 1),
(407, '102', 'Short, sweet, and sets up ACOSF perfectly.', 2),
(408, '102', 'Winter Solstice with the Inner Circle = pure serotonin.', 3),
(409, '103', '768 pages of rebellion, spice, and THAT ending. 💀', 0),
(410, '103', 'The last chapter will make you scream out loud.', 1),
(411, '103', 'Hunt and Bryce are couple goals until everything falls apart.', 2),
(412, '103', 'SJM really said "let me connect ALL my worlds" and did it.', 3),
(413, '104', 'The plot twist in this book changes EVERYTHING. 🗡️', 0),
(414, '104', 'She''s not just an assassin. She''s something much more.', 1),
(415, '104', 'Where the series stops being good and becomes GREAT.', 2),
(416, '104', 'That ending? You''ll need Heir of Fire IMMEDIATELY.', 3),
(417, '105', 'She''s broken. She rebuilds herself. It''s the best book in the series. 🔥', 0),
(418, '105', 'Rowan Whitethorn enters and nothing is the same.', 1),
(419, '105', 'The training montage energy is IMMACULATE.', 2),
(420, '105', 'Where Celaena dies and Aelin is born. 👑', 3),
(421, '106', 'She''s in Hell. Literally. With the devil. Who she might want. 😈', 0),
(422, '106', 'The slow burn gets HOTTER. The trust issues get worse.', 1),
(423, '106', 'Seven demon princes. Seven deadly sins. One witch.', 2),
(424, '106', 'Trust no one. Especially not the pretty ones.', 3),
(425, '107', 'The finale. The reveal. The TWIST. 💀', 0),
(426, '107', 'Three books of slow burn finally EXPLODING.', 1),
(427, '107', 'Wrath is the most patient, possessive demon king ever.', 2),
(428, '107', 'That plot twist reframes the ENTIRE trilogy.', 3),
(429, '108', 'She betrayed him. Now she has to save him. The IRONY. 💔', 0),
(430, '108', 'He''s in a cage. She''s fighting an army. For HIM.', 1),
(431, '108', 'The grovel and redemption arc are ELITE.', 2),
(432, '108', 'Book 2 hits harder than book 1. Didn''t think that was possible.', 3),
(433, '109', 'Tella''s story. She''s messier than Scarlett. We love her more. 💃', 0),
(434, '109', 'The game is bigger. The stakes are real this time.', 1),
(435, '109', 'Legendary is the better Caraval book. I said it.', 2),
(436, '109', 'More romance, more twists, more magic.', 3),
(437, '110', 'The game is over. The real danger begins. 🎭', 0),
(438, '110', 'Both sisters get their endings and it''s PERFECT.', 1),
(439, '110', 'The twists keep coming until the very last page.', 2),
(440, '110', 'A satisfying trilogy finale — rare and precious.', 3),
(441, '111', 'She doesn''t remember him. He remembers everything. 💔', 0),
(442, '111', 'Jacks is the most unhinged love interest and we ADORE him.', 1),
(443, '111', 'The amnesia trope used to maximum emotional damage.', 2),
(444, '111', 'The finale that Jacks deserved.', 3),
(445, '112', 'She makes a deal with the Prince of Hearts. He collects. 🃏', 0),
(446, '112', 'Jacks the villain boyfriend the world didn''t know it needed.', 1),
(447, '112', 'Caraval universe but darker, more romantic, more JACKS.', 2),
(448, '112', '"For you, I''d do terrible things." — yes sir. 🖤', 3),
(449, '113', 'She''s trapped in their world. She might not want to leave. 🎃', 0),
(450, '113', 'Devil''s Night gets darker. And somehow hotter.', 1),
(451, '113', 'Banks is the most complex heroine in the series.', 2),
(452, '113', 'Masks on. Rules off. Welcome back to Thunder Bay.', 3),
(453, '114', 'The best Devil''s Night book. Period. No debate. 🔥', 0),
(454, '114', 'Damon is unhinged. Winter is blind. Together they''re DEVASTATING.', 1),
(455, '114', 'He''s the villain of the series and gets the best love story.', 2),
(456, '114', '612 pages. You won''t put it down once.', 3),
(457, '115', 'The finale. All four couples. One last Devil''s Night. 🌙', 0),
(458, '115', 'Will trapped on an island. Emmy fighting back.', 1),
(459, '115', 'PenDog brings every storyline together perfectly.', 2),
(460, '115', 'The ending of an ERA. You''ll miss Thunder Bay.', 3),
(461, '116', 'He feels no pain. She makes him feel EVERYTHING. 💀', 0),
(462, '116', 'The most emotionally complex Legacy of Gods book.', 1),
(463, '116', 'Creighton is broken in ways that will wreck you.', 2),
(464, '116', 'Dark romance with actual emotional depth. Rare.', 3),
(465, '117', 'He''s older. Bigger. Meaner. She should run. She doesn''t. 😈', 0),
(466, '117', 'The age gap and size difference content is UNMATCHED.', 1),
(467, '117', 'Eli King is the scariest Legacy hero and that''s the appeal.', 2),
(468, '117', 'Rina Kent said "let me make him worse" and we said "yes please."', 3),
(469, '118', 'The MM book Legacy fans were BEGGING for. 🔥', 0),
(470, '118', 'He''s sunshine. He''s darkness. Together they''re explosive.', 1),
(471, '118', 'Rina Kent writes MM with the same intensity and it WORKS.', 2),
(472, '118', 'Nikolai and Jeremy broke the internet for a reason.', 3),
(473, '119', 'She''s a nobody mapmaker. Until she splits the darkness. ☀️', 0),
(474, '119', 'The Darkling is the villain you''ll accidentally root for.', 1),
(475, '119', 'Russian-inspired fantasy that launched an empire.', 2),
(476, '119', 'Read this, then read Six of Crows, then never recover.', 3),
(477, '120', 'She literally goes to Hell. To save someone. Because she''s Alex Stern. 🔥', 0),
(478, '120', 'Darker, wilder, more unhinged than Ninth House.', 1),
(479, '120', 'The magic system gets deeper and creepier.', 2),
(480, '120', 'Bardugo writes adult fantasy like she was born for it.', 3),
(481, '121', 'She discovers she''s a Shadowhunter. Her world was never real. 🗡️', 0),
(482, '121', 'The book that launched an ENTIRE YA fantasy universe.', 1),
(483, '121', 'Jace Wayland — the original golden boy with issues.', 2),
(484, '121', '2000s YA nostalgia in the best possible way.', 3),
(485, '122', 'Victorian London. Shadowhunters. The BEST love triangle ever written. ⚙️', 0),
(486, '122', 'Will and Jem. You''ll love both You''ll suffer for it.', 1),
(487, '122', 'Better than TMI — yes, I said it.', 2),
(488, '122', 'The prose is gorgeous. The heartbreak is worse.', 3),
(489, '123', 'He lied about EVERYTHING. She still wants him. Relatable? 😩', 0),
(490, '123', 'The enemies-to-lovers tension is UNBEARABLE.', 1),
(491, '123', 'Casteel is possessive king and we bow down.', 2),
(492, '123', '623 pages of "I hate you" / "no you don''t" energy.', 3),
(493, '124', 'She discovers what she truly is. It changes EVERYTHING. 👑', 0),
(494, '124', 'Poppy in her power era is magnificent.', 1),
(495, '124', 'More world-building, more spice, more Casteel being Casteel.', 2),
(496, '124', 'The series hits its stride and doesn''t slow down.', 3),
(497, '125', 'She gets out of prison. Her daughter doesn''t know her. 💔', 0),
(498, '125', 'CoHo''s most underrated book and it will DESTROY you.', 1),
(499, '125', 'The redemption arc is earned and heartbreaking.', 2),
(500, '125', 'You''ll cry at least three times. Minimum.', 3),
(501, '126', 'Summer at the beach. A boy with secrets. A girl with nothing to lose. 🌊', 0),
(502, '126', 'Quiet CoHo that sneaks up on you emotionally.', 1),
(503, '126', 'The summer romance you wish you had.', 2),
(504, '126', 'Simple, beautiful, and hits harder than expected.', 3),
(505, '127', 'A haunted bed and breakfast. A girlfriend who''s not quite herself. 👻', 0),
(506, '127', 'CoHo does paranormal and it''s CREEPY.', 1),
(507, '127', 'The twist changes everything you thought you understood.', 2),
(508, '127', 'Verity''s little sister — underrated and unsettling.', 3),
(509, '128', 'Childhood enemies. He became a billionaire. She still hates him. He still wants her. 💰', 0),
(510, '128', 'Lucian is the grumpiest, most protective Knockemout boy.', 1),
(511, '128', '630 pages of enemies to lovers AGONY.', 2),
(512, '128', 'The best Knockemout book — the angst is ELITE.', 3),
(513, '129', 'Apollo and Cassandra undercover at a party where everyone has secrets. 🎭', 0),
(514, '129', 'Fake dating at a murder mystery party. With ACTUAL danger.', 1),
(515, '129', 'The suspense + spice combo is perfect.', 2),
(516, '129', 'Quiet hero who worships her? Yes please.', 3),
(517, '130', 'Married to two people. In Olympus. For power. And pleasure. 💀', 0),
(518, '130', 'The most complex relationship dynamics in Dark Olympus.', 1),
(519, '130', 'Power play, politics, and praise kink. The holy trinity.', 2),
(520, '130', 'Katee Robert''s most ambitious Dark Olympus book.', 3),
(521, '131', 'LA party girl gets sent to a fishing town. Meets a grumpy captain. 🚢', 0),
(522, '131', 'Schitt''s Creek meets romance and it WORKS.', 1),
(523, '131', 'Brendan is the strong silent type who will RUIN you.', 2),
(524, '131', 'She''s a mess. He thinks she''s perfect. We agree.', 3),
(525, '132', 'The player who falls for the one girl he can''t have. 🎣', 0),
(526, '132', 'Fox is a reformed f-boy and his redemption arc is BEAUTIFUL.', 1),
(527, '132', 'Friends to lovers where he''s been in love the WHOLE time.', 2),
(528, '132', 'Better than book 1. I said what I said.', 3),
(529, '133', 'She writes him love letters she never sends. He finds them. 💌', 0),
(530, '133', 'Napa Valley setting, wine, and a professor who can''t stop staring.', 1),
(531, '133', 'She''s chaos in overalls. He''s order in a button-down.', 2),
(532, '133', 'Tessa Bailey writes the BEST grumpy heroes. This proves it.', 3),
(533, '134', 'They hate each other. They get married. For a vineyard. Obviously. 🍷', 0),
(534, '134', 'Marriage of convenience where the inconvenience is FEELINGS.', 1),
(535, '134', 'The banter is sharp enough to cut glass.', 2),
(536, '134', 'Enemies to spouses to lovers. The best order.', 3),
(537, '135', 'She''s a surgeon. He''s a small-town carpenter. Her family disapproves. 💔', 0),
(538, '135', 'The class difference angle makes it so much more real.', 1),
(539, '135', 'Daniel is the sweetest, most patient man in fiction.', 2),
(540, '135', 'Funny until it punches you in the heart. Classic Abby.', 3),
(541, '136', 'They start writing letters. He falls in love through WORDS. 💌', 0),
(542, '136', 'Fake dating a coworker who writes the most beautiful letters.', 1),
(543, '136', 'Jacob is neurodivergent rep done with so much love and care.', 2),
(544, '136', 'The best Abby Jimenez book. Ready to fight about it.', 3),
(545, '137', 'Every person they date finds their soulmate... after dating them. 😅', 0),
(546, '137', 'Two cursed people try to break the curse by dating each other.', 1),
(547, '137', 'The premise is SO fun and the execution is even better.', 2),
(548, '137', 'Abby Jimenez never misses. This is more proof.', 3),
(549, '138', 'Best friends. He''s an NFL quarterback. She''s oblivious. EVERYONE knows except her. 🏈', 0),
(550, '138', 'The most wholesome sports romance you''ll ever read.', 1),
(551, '138', 'He''s been in love with her forever and it''s SO obvious.', 2),
(552, '138', 'Zero angst, all fluff. Sometimes that''s exactly what you need.', 3),
(553, '139', 'Small town. Grumpy neighbor. She''s determined to make him smile. 😊', 0),
(554, '139', 'The forced proximity is ADORABLE.', 1),
(555, '139', 'He tries so hard to not like her. He fails spectacularly.', 2),
(556, '139', 'Pure serotonin in book form.', 3),
(557, '140', 'Famous singer runs away to a small town. Grumpy pie shop owner takes her in. 🥧', 0),
(558, '140', 'She''s hiding from fame. He doesn''t care who she is.', 1),
(559, '140', 'The most comforting book on this list.', 2),
(560, '140', 'Read this when you need a hug in book form. 🤗', 3)
ON CONFLICT DO NOTHING;