/*
  # Seed catalog_tags table
  Inserts all tropes, genres, and moods from the static books database.
*/
INSERT INTO catalog_tags (id, slug, name, type) VALUES
('1', 'enemies-to-lovers', 'Enemies To Lovers', 'trope'),
('2', 'forced-proximity', 'Forced Proximity', 'trope'),
('3', 'touch-her-and-die', 'Touch Her And Die', 'trope'),
('4', 'magical-bond', 'Magical Bond', 'trope'),
('5', 'fated-mates', 'Fated Mates', 'trope'),
('6', 'chosen-one', 'Chosen One', 'trope'),
('7', 'he-falls-first', 'He Falls First', 'trope'),
('8', 'who-did-this-to-you', 'Who Did This To You', 'trope'),
('9', 'fantasy-romance', 'Fantasy Romance', 'genre'),
('10', 'romantasy', 'Romantasy', 'genre'),
('11', 'intense', 'Intense', 'mood'),
('12', 'steamy', 'Steamy', 'mood'),
('13', 'adventurous', 'Adventurous', 'mood'),
('14', 'rebellion', 'Rebellion', 'trope'),
('15', 'dark-protector', 'Dark Protector', 'trope'),
('16', 'pining', 'Pining', 'trope'),
('17', 'angsty', 'Angsty', 'mood'),
('18', 'redemption-arc', 'Redemption Arc', 'trope'),
('19', 'captive-romance', 'Captive Romance', 'trope'),
('20', 'emotional', 'Emotional', 'mood'),
('21', 'slow-burn', 'Slow Burn', 'trope'),
('22', 'found-family', 'Found Family', 'trope'),
('23', 'broken-hero', 'Broken Hero', 'trope'),
('24', 'empowering', 'Empowering', 'mood'),
('25', 'war-backdrop', 'War Backdrop', 'trope'),
('26', 'hurt-comfort', 'Hurt Comfort', 'trope'),
('27', 'bratty-heroine', 'Bratty Heroine', 'trope'),
('28', 'size-difference', 'Size Difference', 'trope'),
('29', 'forbidden-love', 'Forbidden Love', 'trope'),
('30', 'secret-identity', 'Secret Identity', 'trope'),
('31', 'possessive-hero', 'Possessive Hero', 'trope'),
('32', 'obsessed-hero', 'Obsessed Hero', 'trope'),
('33', 'young-adult', 'Young Adult', 'genre'),
('34', 'morally-grey', 'Morally Grey', 'trope'),
('35', 'rivals', 'Rivals', 'trope'),
('36', 'power-imbalance', 'Power Imbalance', 'trope'),
('37', 'royalty', 'Royalty', 'trope'),
('38', 'dark', 'Dark', 'mood'),
('39', 'witch-romance', 'Witch Romance', 'trope'),
('40', 'detective-romance', 'Detective Romance', 'trope'),
('41', 'mysterious', 'Mysterious', 'mood'),
('42', 'love-triangle', 'Love Triangle', 'trope'),
('43', 'coming-of-age', 'Coming Of Age', 'trope'),
('44', 'arranged-marriage', 'Arranged Marriage', 'trope'),
('45', 'forced-marriage', 'Forced Marriage', 'trope'),
('46', 'double-cross', 'Double Cross', 'trope'),
('47', 'dark-secret', 'Dark Secret', 'trope'),
('48', 'beautiful-prose', 'Beautiful Prose', 'trope'),
('49', 'creepy-atmosphere', 'Creepy Atmosphere', 'trope'),
('50', 'everyone-is-suspect', 'Everyone Is Suspect', 'trope'),
('51', 'trapped', 'Trapped', 'trope'),
('52', 'villain-romance', 'Villain Romance', 'trope'),
('53', 'stalker-romance', 'Stalker Romance', 'trope'),
('54', 'cat-and-mouse', 'Cat And Mouse', 'trope'),
('55', 'dark-romance', 'Dark Romance', 'genre'),
('56', 'romantic-suspense', 'Romantic Suspense', 'genre'),
('57', 'revenge', 'Revenge', 'trope'),
('58', 'conspiracy', 'Conspiracy', 'trope'),
('59', 'heartbreaking', 'Heartbreaking', 'mood'),
('60', 'masked-man', 'Masked Man', 'trope'),
('61', 'dominant-hero', 'Dominant Hero', 'trope'),
('62', 'bully-romance', 'Bully Romance', 'genre'),
('63', 'new-adult', 'New Adult', 'genre'),
('64', 'reverse-harem', 'Reverse Harem', 'trope'),
('65', 'mafia-boss', 'Mafia Boss', 'trope'),
('66', 'mafia-romance', 'Mafia Romance', 'genre'),
('67', 'grumpy-sunshine', 'Grumpy Sunshine', 'trope'),
('68', 'serial-killer', 'Serial Killer', 'trope'),
('69', 'road-trip', 'Road Trip', 'trope'),
('70', 'rom-com', 'Rom Com', 'genre'),
('71', 'funny', 'Funny', 'mood'),
('72', 'childhood-friends', 'Childhood Friends', 'trope'),
('73', 'age-gap', 'Age Gap', 'trope'),
('74', 'contemporary-romance', 'Contemporary Romance', 'genre'),
('75', 'epistolary', 'Epistolary', 'trope'),
('76', 'brother-best-friend', 'Brother Best Friend', 'trope'),
('77', 'billionaire', 'Billionaire', 'trope'),
('78', 'bodyguard', 'Bodyguard', 'trope'),
('79', 'bet-dare', 'Bet Dare', 'trope'),
('80', 'miscommunication', 'Miscommunication', 'trope'),
('81', 'fake-dating', 'Fake Dating', 'trope'),
('82', 'ceo-romance', 'Ceo Romance', 'trope'),
('83', 'second-chance', 'Second Chance', 'trope'),
('84', 'domestic-thriller', 'Domestic Thriller', 'trope'),
('85', 'single-parent', 'Single Parent', 'trope'),
('86', 'one-that-got-away', 'One That Got Away', 'trope'),
('87', 'cozy', 'Cozy', 'mood'),
('88', 'friends-to-lovers', 'Friends To Lovers', 'trope'),
('89', 'multiple-timelines', 'Multiple Timelines', 'trope'),
('90', 'unrequited-love', 'Unrequited Love', 'trope'),
('91', 'unreliable-narrator', 'Unreliable Narrator', 'trope'),
('92', 'plot-twist', 'Plot Twist', 'trope'),
('93', 'psychological-thriller', 'Psychological Thriller', 'trope'),
('94', 'gone-girl-vibes', 'Gone Girl Vibes', 'trope'),
('95', 'last-page-twist', 'Last Page Twist', 'trope'),
('96', 'book-within-book', 'Book Within Book', 'trope'),
('97', 'thriller', 'Thriller', 'genre'),
('98', 'amnesia', 'Amnesia', 'trope'),
('99', 'boss-employee', 'Boss Employee', 'trope'),
('100', 'bookish-heroine', 'Bookish Heroine', 'trope'),
('101', 'opposites-attract', 'Opposites Attract', 'trope'),
('102', 'fluffy', 'Fluffy', 'mood'),
('103', 'coworkers-to-lovers', 'Coworkers To Lovers', 'trope'),
('104', 'neighbors', 'Neighbors', 'trope'),
('105', 'only-one-bed', 'Only One Bed', 'trope'),
('106', 'marriage-of-convenience', 'Marriage Of Convenience', 'trope'),
('107', 'sports-romance', 'Sports Romance', 'genre'),
('108', 'anti-hero', 'Anti Hero', 'trope'),
('109', 'tragic-ending', 'Tragic Ending', 'trope'),
('110', 'literary-fiction', 'Literary Fiction', 'genre'),
('111', 'historical-romance', 'Historical Romance', 'genre'),
('112', 'magical-realism', 'Magical Realism', 'trope'),
('113', 'based-on-true-story', 'Based On True Story', 'trope'),
('114', 'family-saga', 'Family Saga', 'trope'),
('115', 'social-commentary', 'Social Commentary', 'trope'),
('116', 'philosophical', 'Philosophical', 'trope'),
('117', 'dystopia', 'Dystopia', 'trope'),
('118', 'praise-kink', 'Praise Kink', 'trope'),
('119', 'whodunit', 'Whodunit', 'trope'),
('120', 'heist', 'Heist', 'trope'),
('121', 'vampire-romance', 'Vampire Romance', 'trope'),
('122', 'werewolf-romance', 'Werewolf Romance', 'trope'),
('123', 'paranormal-romance', 'Paranormal Romance', 'genre'),
('124', 'teacher-student', 'Teacher Student', 'trope'),
('125', 'time-travel', 'Time Travel', 'trope'),
('126', 'survival', 'Survival', 'trope'),
('127', 'portal-fantasy', 'Portal Fantasy', 'trope'),
('128', 'holiday-romance', 'Holiday Romance', 'trope'),
('129', 'spy-romance', 'Spy Romance', 'trope')
ON CONFLICT DO NOTHING;
